// Generated by `bun init`

// Type declarations for Bun.markdown API (added in Bun 1.3.8)
// Using module augmentation to extend the existing "bun" module types
declare module "bun" {
  interface MarkdownReactOptions {
    /** Custom component for links */
    a?: (props: { href?: string; children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for paragraphs */
    p?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for headings */
    h1?: (props: { children?: React.ReactNode }) => React.ReactNode;
    h2?: (props: { children?: React.ReactNode }) => React.ReactNode;
    h3?: (props: { children?: React.ReactNode }) => React.ReactNode;
    h4?: (props: { children?: React.ReactNode }) => React.ReactNode;
    h5?: (props: { children?: React.ReactNode }) => React.ReactNode;
    h6?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for inline code */
    code?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for code blocks */
    pre?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for bold text */
    strong?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for italic text */
    em?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for unordered lists */
    ul?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for ordered lists */
    ol?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for list items */
    li?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for blockquotes */
    blockquote?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for images */
    img?: (props: { src?: string; alt?: string }) => React.ReactNode;
    /** Custom component for horizontal rules */
    hr?: () => React.ReactNode;
    /** Custom component for tables */
    table?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for table headers */
    thead?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for table body */
    tbody?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for table rows */
    tr?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for table header cells */
    th?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** Custom component for table cells */
    td?: (props: { children?: React.ReactNode }) => React.ReactNode;
    /** React version (default 19) */
    reactVersion?: 18 | 19;
  }

  interface MarkdownHtmlOptions {
    /** Add IDs to headings */
    headingIds?: boolean;
    /** Autolink headings */
    autolinkHeadings?: boolean;
  }

  interface Markdown {
    /** Render markdown to React elements */
    react(markdown: string, options?: MarkdownReactOptions): React.ReactNode;
    /** Render markdown to HTML string */
    html(markdown: string, options?: MarkdownHtmlOptions): string;
  }

  const markdown: Markdown;
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
